import Navbar from "../components/Navbar";
import { Roboto } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

const font = Roboto({
  weight: ["400", "500"],
  style: ["italic"],
  subsets: ["latin"],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={font.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
